### ISSUE TITLE
Can't right click wandering traders

### ISSUE THREAD

**Issue by RealKomander** [FancyMcPlugins/FancyNpcs#124]
Server version - paper 1.20.4
Plugin version - 2.0.9

Here's the config of my NPC:
[npcs.txt](https://github.com/user-attachments/files/15858237/npcs.txt)

If I change its type, everything works, so I guess this is a bug

**Comment by Grabsky** [comment]
Should be already fixed in https://github.com/FancyMcPlugins/FancyNpcs/commit/d384a389211a6ea0055d067d882841aee82d7168. Please update FancyNpcs to **2.1.0** or latest development build and comment on this issue if resolved.

**Latest Release**: https://github.com/FancyMcPlugins/FancyNpcs/releases/latest
**Latest Development Build**: https://jenkins.fancyplugins.de/job/FancyNpcs/

**Comment by RealKomander** [comment]
2.1.0 is incompatible with 1.20.4. It asks for java 21, but it doesn't work with server itself

**Comment by Grabsky** [comment]
> 2.1.0 is incompatible with 1.20.4. It asks for java 21, but it doesn't work with the server itself

@RealKomander 
Works fine for me. Tested locally with Paper 1.20.4, Java 21 and FancyNpcs 2.1.0 downloaded from Modrinth.

**Comment by OliverSchlueter** [comment]
Does this still happen in the latest version? We can not reproduce it.

If the bug still exists for you, please reopen this issue or write a comment
