### ISSUE TITLE
Some entities can't hide their names properly

### ISSUE THREAD

**Issue by xiaozhangup** [FancyMcPlugins/FancyNpcs#186]
![image](https://github.com/user-attachments/assets/9fd9660b-81ce-40d3-ac09-e8cadc7da890)

Like this, I've set them to @none.

**Comment by OliverSchlueter** [comment]
Should be fixed in dev build #223

**Comment by Grabsky** [comment]
Can confirm this was fixed in cdc11ca8ec01cc4ca5339cfb612c2d80d75e0ab7.
![Screenshot from 2024-11-17 16-15-52](https://github.com/user-attachments/assets/f2e40fcd-33a8-4de5-ac5b-1d465192c6b3)
![Screenshot from 2024-11-17 16-16-00](https://github.com/user-attachments/assets/214d0218-39c0-442f-9c39-eb7aaa352b11)
